"""Add localized cleanup copy without changing existing translations."""
import json
from pathlib import Path

COPY = {
 'strings': ['Clean unused artwork', 'Remove cached Perfect Hero and Banner sources for removed games. Steam artwork and original backups are kept.', '{count} files removed ({size} MiB).', 'Unavailable libraries and files were kept. Please retry when Steam libraries are accessible.'],
 'it': ['Pulisci artwork inutilizzati', 'Rimuovi le sorgenti memorizzate di Perfect Hero e Banner dei giochi rimossi. Artwork di Steam e backup originali vengono conservati.', '{count} file rimossi ({size} MiB).', 'Librerie e file non accessibili sono stati conservati. Riprova quando le librerie Steam sono disponibili.'],
 'fr': ['Nettoyer les illustrations inutilisées', 'Supprime les sources Perfect Hero et Banner en cache des jeux retirés. Les illustrations Steam et les sauvegardes originales sont conservées.', '{count} fichiers supprimés ({size} MiB).', 'Les bibliothèques et fichiers inaccessibles ont été conservés. Réessayez quand les bibliothèques Steam sont accessibles.'],
 'de': ['Ungenutzte Grafiken bereinigen', 'Entfernt zwischengespeicherte Perfect-Hero- und Banner-Quellen entfernter Spiele. Steam-Grafiken und Originalbackups bleiben erhalten.', '{count} Dateien entfernt ({size} MiB).', 'Nicht erreichbare Bibliotheken und Dateien wurden behalten. Versuche es erneut, wenn die Steam-Bibliotheken erreichbar sind.'],
 'es': ['Limpiar imágenes sin usar', 'Elimina las fuentes de Perfect Hero y Banner en caché de los juegos eliminados. Conserva las imágenes de Steam y las copias originales.', '{count} archivos eliminados ({size} MiB).', 'Se conservaron las bibliotecas y archivos no accesibles. Vuelve a intentarlo cuando las bibliotecas de Steam estén disponibles.'],
 'pt': ['Limpar imagens não utilizadas', 'Remove as fontes de Perfect Hero e Banner em cache dos jogos removidos. As imagens do Steam e as cópias originais são mantidas.', '{count} ficheiros removidos ({size} MiB).', 'As bibliotecas e os ficheiros inacessíveis foram mantidos. Tenta novamente quando as bibliotecas do Steam estiverem acessíveis.'],
 'pt-br': ['Limpar imagens não utilizadas', 'Remove as fontes de Perfect Hero e Banner em cache dos jogos removidos. As imagens do Steam e os backups originais são mantidos.', '{count} arquivos removidos ({size} MiB).', 'As bibliotecas e os arquivos inacessíveis foram mantidos. Tente novamente quando as bibliotecas do Steam estiverem acessíveis.'],
 'nl': ['Ongebruikte afbeeldingen opruimen', 'Verwijdert Perfect Hero- en Banner-bronnen in de cache voor verwijderde spellen. Steam-afbeeldingen en originele back-ups blijven behouden.', '{count} bestanden verwijderd ({size} MiB).', 'Niet-beschikbare bibliotheken en bestanden zijn behouden. Probeer opnieuw wanneer de Steam-bibliotheken beschikbaar zijn.'],
 'pl': ['Usuń nieużywane grafiki', 'Usuwa źródła Perfect Hero i Banner z pamięci podręcznej usuniętych gier. Grafiki Steam i oryginalne kopie zapasowe pozostają.', 'Usunięto {count} plików ({size} MiB).', 'Zachowano niedostępne biblioteki i pliki. Spróbuj ponownie, gdy biblioteki Steam będą dostępne.'],
 'ru': ['Удалить неиспользуемые изображения', 'Удаляет кешированные исходники Perfect Hero и Banner для удалённых игр. Изображения Steam и резервные копии оригиналов сохраняются.', 'Удалено файлов: {count} ({size} MiB).', 'Недоступные библиотеки и файлы сохранены. Повторите попытку, когда библиотеки Steam станут доступны.'],
 'uk': ['Видалити невикористані зображення', 'Видаляє кешовані джерела Perfect Hero і Banner для видалених ігор. Зображення Steam та резервні копії оригіналів зберігаються.', 'Видалено файлів: {count} ({size} MiB).', 'Недоступні бібліотеки та файли збережено. Повторіть спробу, коли бібліотеки Steam стануть доступними.'],
 'ja': ['未使用のアートワークを削除', '削除したゲームの Perfect Hero と Banner のキャッシュ素材を削除します。Steam の画像と元のバックアップは保持します。', '{count} 個のファイルを削除しました（{size} MiB）。', 'アクセスできないライブラリとファイルは保持しました。Steam ライブラリにアクセスできる状態で再試行してください。'],
 'ko': ['사용하지 않는 아트워크 정리', '삭제된 게임의 Perfect Hero 및 Banner 캐시 원본을 제거합니다. Steam 아트워크와 원본 백업은 유지됩니다.', '{count}개 파일 삭제됨 ({size} MiB).', '접근할 수 없는 라이브러리와 파일은 유지했습니다. Steam 라이브러리에 접근할 수 있을 때 다시 시도하세요.'],
 'zh-cn': ['清理未使用的美术资源', '删除已移除游戏的 Perfect Hero 和 Banner 缓存素材。保留 Steam 图片和原始备份。', '已删除 {count} 个文件（{size} MiB）。', '无法访问的库和文件已保留。请在 Steam 库可访问时重试。'],
 'zh-tw': ['清理未使用的美術資源', '刪除已移除遊戲的 Perfect Hero 和 Banner 快取素材。保留 Steam 圖片和原始備份。', '已刪除 {count} 個檔案（{size} MiB）。', '無法存取的收藏庫和檔案已保留。請在 Steam 收藏庫可存取時重試。'],
 'ar': ['تنظيف الصور غير المستخدمة', 'يزيل مصادر Perfect Hero وBanner المخزنة للألعاب المحذوفة. تُحفظ صور Steam والنسخ الاحتياطية الأصلية.', 'تم حذف {count} ملف ({size} MiB).', 'تم الاحتفاظ بالمكتبات والملفات غير المتاحة. أعد المحاولة عندما تصبح مكتبات Steam متاحة.'],
 'bg': ['Изчистване на неизползваните изображения', 'Премахва кешираните източници на Perfect Hero и Banner за премахнати игри. Изображенията на Steam и оригиналните резервни копия се запазват.', 'Премахнати са {count} файла ({size} MiB).', 'Недостъпните библиотеки и файлове са запазени. Опитайте отново, когато библиотеките на Steam са достъпни.'],
 'cs': ['Vyčistit nepoužívané obrázky', 'Odstraní zdroje Perfect Hero a Banner v mezipaměti pro odebrané hry. Obrázky Steamu a původní zálohy zůstanou zachovány.', 'Odstraněno {count} souborů ({size} MiB).', 'Nedostupné knihovny a soubory byly zachovány. Zkuste to znovu, až budou knihovny Steamu dostupné.'],
 'da': ['Ryd ubrugte billeder', 'Fjerner cachelagrede Perfect Hero- og Banner-kilder for fjernede spil. Steam-billeder og originale sikkerhedskopier beholdes.', '{count} filer fjernet ({size} MiB).', 'Utilgængelige biblioteker og filer blev beholdt. Prøv igen, når Steam-bibliotekerne er tilgængelige.'],
 'el': ['Καθαρισμός μη χρησιμοποιούμενων εικόνων', 'Αφαιρεί τις αποθηκευμένες πηγές Perfect Hero και Banner για παιχνίδια που αφαιρέθηκαν. Οι εικόνες Steam και τα αρχικά αντίγραφα διατηρούνται.', 'Αφαιρέθηκαν {count} αρχεία ({size} MiB).', 'Οι μη διαθέσιμες βιβλιοθήκες και τα αρχεία διατηρήθηκαν. Δοκιμάστε ξανά όταν οι βιβλιοθήκες Steam είναι διαθέσιμες.'],
 'fi': ['Poista käyttämättömät kuvat', 'Poistaa poistettujen pelien Perfect Hero- ja Banner-lähteet välimuistista. Steam-kuvat ja alkuperäiset varmuuskopiot säilytetään.', '{count} tiedostoa poistettu ({size} MiB).', 'Kirjastot ja tiedostot, joihin ei saada yhteyttä, säilytettiin. Yritä uudelleen, kun Steam-kirjastot ovat käytettävissä.'],
 'hu': ['Nem használt képek törlése', 'Eltávolítja a törölt játékok gyorsítótárazott Perfect Hero és Banner forrásait. A Steam képei és az eredeti biztonsági másolatok megmaradnak.', '{count} fájl törölve ({size} MiB).', 'A nem elérhető könyvtárak és fájlok megmaradtak. Próbáld újra, amikor a Steam-könyvtárak elérhetők.'],
 'id': ['Bersihkan gambar tidak terpakai', 'Menghapus sumber Perfect Hero dan Banner yang tersimpan untuk game yang dihapus. Gambar Steam dan cadangan asli tetap disimpan.', '{count} berkas dihapus ({size} MiB).', 'Pustaka dan berkas yang tidak tersedia tetap disimpan. Coba lagi saat pustaka Steam dapat diakses.'],
 'ms': ['Bersihkan imej tidak digunakan', 'Membuang sumber Perfect Hero dan Banner dalam cache untuk permainan yang dibuang. Imej Steam dan sandaran asal dikekalkan.', '{count} fail dibuang ({size} MiB).', 'Pustaka dan fail yang tidak tersedia dikekalkan. Cuba lagi apabila pustaka Steam boleh diakses.'],
 'no': ['Rydd ubrukte bilder', 'Fjerner mellomlagrede Perfect Hero- og Banner-kilder for fjernede spill. Steam-bilder og originale sikkerhetskopier beholdes.', '{count} filer fjernet ({size} MiB).', 'Utilgjengelige biblioteker og filer ble beholdt. Prøv igjen når Steam-bibliotekene er tilgjengelige.'],
 'ro': ['Curăță imaginile neutilizate', 'Elimină sursele Perfect Hero și Banner din cache pentru jocurile șterse. Imaginile Steam și copiile originale sunt păstrate.', '{count} fișiere eliminate ({size} MiB).', 'Bibliotecile și fișierele indisponibile au fost păstrate. Reîncearcă atunci când bibliotecile Steam sunt accesibile.'],
 'sv': ['Rensa oanvända bilder', 'Tar bort cachade Perfect Hero- och Banner-källor för borttagna spel. Steam-bilder och ursprungliga säkerhetskopior behålls.', '{count} filer borttagna ({size} MiB).', 'Otillgängliga bibliotek och filer behölls. Försök igen när Steam-biblioteken är tillgängliga.'],
 'th': ['ล้างภาพที่ไม่ได้ใช้', 'ลบต้นฉบับ Perfect Hero และ Banner ที่แคชไว้สำหรับเกมที่นำออก โดยเก็บภาพ Steam และข้อมูลสำรองต้นฉบับไว้', 'ลบ {count} ไฟล์แล้ว ({size} MiB)', 'เก็บคลังและไฟล์ที่เข้าถึงไม่ได้ไว้ โปรดลองอีกครั้งเมื่อเข้าถึงคลัง Steam ได้'],
 'tr': ['Kullanılmayan görselleri temizle', 'Kaldırılan oyunların önbellekteki Perfect Hero ve Banner kaynaklarını siler. Steam görselleri ve özgün yedekler korunur.', '{count} dosya silindi ({size} MiB).', 'Erişilemeyen kütüphaneler ve dosyalar korundu. Steam kütüphanelerine erişilebildiğinde yeniden deneyin.'],
 'vi': ['Dọn ảnh không sử dụng', 'Xóa nguồn Perfect Hero và Banner trong bộ nhớ đệm của trò chơi đã xóa. Giữ lại ảnh Steam và bản sao lưu gốc.', 'Đã xóa {count} tệp ({size} MiB).', 'Các thư viện và tệp không truy cập được vẫn được giữ. Thử lại khi có thể truy cập thư viện Steam.'],
}
COPY['es-419'] = COPY['es']
KEYS = ['PA_CLEAN_UNUSED', 'PA_CLEAN_UNUSED_DESC', 'PA_CLEAN_UNUSED_RESULT', 'PA_CLEAN_UNUSED_PARTIAL']
root = Path(__file__).resolve().parents[1] / 'src/i18n'
for path in root.glob('*.json'):
    data = json.loads(path.read_text(encoding='utf-8-sig'))
    data.update(zip(KEYS, COPY[path.stem]))
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Localized {len(COPY)} catalogs.')
